# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uimodify.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from dbase import *


class Ui_Modify(object):
    def setupUi(self, Modify):
        Modify.setObjectName("Modify")
        Modify.resize(400, 300)
        Modify.setMinimumSize(QtCore.QSize(400, 300))
        Modify.setMaximumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setPointSize(10)
        Modify.setFont(font)
        self.label = QtWidgets.QLabel(Modify)
        self.label.setGeometry(QtCore.QRect(5, 16, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Modify)
        self.label_2.setGeometry(QtCore.QRect(20, 72, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Modify)
        self.label_3.setGeometry(QtCore.QRect(20, 114, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Modify)
        self.label_4.setGeometry(QtCore.QRect(20, 152, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Modify)
        self.label_5.setGeometry(QtCore.QRect(22, 191, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.groupBox = QtWidgets.QGroupBox(Modify)
        self.groupBox.setGeometry(QtCore.QRect(10, 253, 381, 41))
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.btnDelete = QtWidgets.QPushButton(self.groupBox)
        self.btnDelete.setGeometry(QtCore.QRect(6, 10, 75, 23))
        self.btnDelete.setObjectName("btnDelete")
        self.btnOk = QtWidgets.QPushButton(self.groupBox)
        self.btnOk.setGeometry(QtCore.QRect(210, 10, 75, 23))
        self.btnOk.setDefault(True)
        self.btnOk.setObjectName("btnOk")
        self.btnCancel = QtWidgets.QPushButton(self.groupBox)
        self.btnCancel.setGeometry(QtCore.QRect(300, 10, 75, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.lineEdit = QtWidgets.QLineEdit(Modify)
        self.lineEdit.setGeometry(QtCore.QRect(170, 72, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Modify)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 112, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Modify)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 151, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.comboBox = QtWidgets.QComboBox(Modify)
        self.comboBox.setGeometry(QtCore.QRect(170, 191, 211, 22))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(Modify)
        QtCore.QMetaObject.connectSlotsByName(Modify)

    def retranslateUi(self, Modify):
        _translate = QtCore.QCoreApplication.translate
        Modify.setWindowTitle(_translate("Modify", "Додавання, редагування даних ..."))
        self.label.setText(_translate("Modify", "Додавання, редагування даних  результатів аналізу"))
        self.label_2.setText(_translate("Modify", "Номер серії"))
        self.label_3.setText(_translate("Modify", "Проміжна продукція"))
        self.label_4.setText(_translate("Modify", "Готова продукція"))
        self.label_5.setText(_translate("Modify", "Країна"))
        self.btnDelete.setText(_translate("Modify", "Вилучити"))
        self.btnOk.setText(_translate("Modify", "Прийняти"))
        self.btnCancel.setText(_translate("Modify", "Відміна"))

